### ISSUE TITLE
Create a Markdown file Inspector

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/8woc2018-jvm#368]
## User Story

As a manager, I would like to have a process that automatically recognizes if a file is Markdown or USFM.

**Comment by aunger** [comment]
Consider whether this should select based on file extension or on the manifest's `format: 'text/markdown'`.

*Answer: yes, use MIME.*

Maybe also ask Joe if he had some mechanism other than an `if` conditional in mind.

*Answer: the conditional as-is is probably appropriate.*
