### ISSUE TITLE
"Welcome Back" internationalization

### ISSUE THREAD

**Issue by fucata55** [WycliffeAssociates/8woc2018-jvm#41]
Create an internationalization of "Welcome Back" underneath the big profile icon at Welcome Screen

**Comment by k-horton** [comment]
Are you guys already working on this? If not, I can go ahead and get started on it.

**Comment by natibekele** [comment]
we haven't started on it as yet. so you can go ahead and do it @k-horton

**Comment by Redmayspecial** [comment]
No longer applicable to the code base
