### ISSUE TITLE
Populate Language Class

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/8woc2018-jvm#50]
Provide a Language class with
- [ ] Name
- [ ] Slug
- [ ] ID
- [ ] Type
- [ ] Anglicized Name

**Comment by mbr4477** [comment]
Issue moved to [WycliffeAssociates/8woc2018-common #20](https://github.com/WycliffeAssociates/8woc2018-common/issues/20) via [**ZenHub**](https://www.zenhub.com/)
