### ISSUE TITLE
Provision a user class

### ISSUE THREAD

**Issue by Redmayspecial** [WycliffeAssociates/8woc2018-jvm#53]
Provide a User Class with
- [ ] id
- [ ] audioHash
- [ ] audioPath
- [ ] sourceLang
- [ ] targetLang
- [ ] userPreferences

**Comment by mbr4477** [comment]
Issue moved to [WycliffeAssociates/8woc2018-common #18](https://github.com/WycliffeAssociates/8woc2018-common/issues/18) via [**ZenHub**](https://www.zenhub.com/)
